apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-orchestrator-v1
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0" 
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/dtwo-qa/mcp-orchestrator-v1:latest
        ports:
        - containerPort: 4001
          name: http1
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4001"
        - name: CACHE_TTL
          value: "3600"
        - name: CHARGEBEE_ENABLED
          value: "false"
        - name: HUBSPOT_ENABLED
          value: "false"
        - name: FIREBASE_ENABLED
          value: "false"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /graphql
            port: 4001
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /graphql
            port: 4001
          initialDelaySeconds: 10
          timeoutSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true
