apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-orchestrator-v1
  labels:
    cloud.google.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/mcp-orchestrator-v1:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GRAPHQL_ENDPOINT
          value: "/graphql"
        - name: CACHE_TTL
          value: "7200"
        - name: CACHE_MAX_SIZE
          value: "1000"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        # MCP Configuration - these will be set via gcloud command
        - name: CHARGEBEE_ENABLED
          value: "true"
        - name: HUBSPOT_ENABLED
          value: "true"
        - name: FIREBASE_ENABLED
          value: "true"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
