steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:latest',
      '.'
    ]

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:$BUILD_ID'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'mcp-orchestrator-v1',
      '--image', 'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--concurrency', '100',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production,PORT=8080,GRAPHQL_ENDPOINT=/graphql,CACHE_TTL=7200,LOG_LEVEL=info'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/mcp-orchestrator-v1:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: 1200s
